/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import Cliente.ConexionCliente;
import Ventanas.Ventana_EmpezarPartida;
import Ventanas.Ventana_Opcion2_VerT;
import Ventanas.Ventana_VerPartidaSinTerminar;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author mario
 */
public class AppModificada extends javax.swing.JFrame {

    ConexionCliente miCliente = ConexionCliente.getCliente();

    public ConexionCliente getMiCliente() {
        return miCliente;
    }

    /**
     * Creates new form NewJFrame
     */
    public AppModificada() {
        initComponents();
        initStyle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroun = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        Separador = new javax.swing.JSeparator();
        EmpezarPartidaBoton = new javax.swing.JButton();
        VerPartidasTerminadasBoton = new javax.swing.JButton();
        VerPartidasSinTerminarBoton = new javax.swing.JButton();
        SalirBoton = new javax.swing.JButton();
        Icono = new javax.swing.JLabel();
        Barra = new javax.swing.JPanel();
        GitHubTexto = new javax.swing.JLabel();
        emailTexto = new javax.swing.JLabel();
        textoEjercicio = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1036, 652));

        backgroun.setBackground(new java.awt.Color(255, 255, 255));
        backgroun.setPreferredSize(new java.awt.Dimension(1020, 640));

        menu.setBackground(new java.awt.Color(204, 41, 41));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        Separador.setBackground(new java.awt.Color(255, 255, 255));
        Separador.setForeground(new java.awt.Color(255, 255, 255));

        EmpezarPartidaBoton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EmpezarPartidaBoton.setForeground(new java.awt.Color(255, 255, 255));
        EmpezarPartidaBoton.setText("Empezar Partida");
        EmpezarPartidaBoton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        EmpezarPartidaBoton.setBorderPainted(false);
        EmpezarPartidaBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpezarPartidaBoton.setIconTextGap(10);
        EmpezarPartidaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpezarPartidaBotonActionPerformed(evt);
            }
        });

        VerPartidasTerminadasBoton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        VerPartidasTerminadasBoton.setForeground(new java.awt.Color(255, 255, 255));
        VerPartidasTerminadasBoton.setText("Ver Partidaa Terminadas");
        VerPartidasTerminadasBoton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        VerPartidasTerminadasBoton.setBorderPainted(false);
        VerPartidasTerminadasBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerPartidasTerminadasBoton.setIconTextGap(10);
        VerPartidasTerminadasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPartidasTerminadasBotonActionPerformed(evt);
            }
        });

        VerPartidasSinTerminarBoton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        VerPartidasSinTerminarBoton.setForeground(new java.awt.Color(255, 255, 255));
        VerPartidasSinTerminarBoton.setText("Ver Partidas Sin Terminadas");
        VerPartidasSinTerminarBoton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        VerPartidasSinTerminarBoton.setBorderPainted(false);
        VerPartidasSinTerminarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerPartidasSinTerminarBoton.setIconTextGap(10);
        VerPartidasSinTerminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPartidasSinTerminarBotonActionPerformed(evt);
            }
        });

        SalirBoton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SalirBoton.setForeground(new java.awt.Color(255, 255, 255));
        SalirBoton.setText("Salir");
        SalirBoton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        SalirBoton.setBorderPainted(false);
        SalirBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirBoton.setIconTextGap(10);
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        Icono.setIcon(new javax.swing.ImageIcon("C:\\Users\\DAW_M\\Documents\\NetBeansProjects\\Juego-Batalla-Naval\\src\\main\\img\\barco-pirata (1).png")); // NOI18N

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(Icono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VerPartidasTerminadasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EmpezarPartidaBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerPartidasSinTerminarBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Icono)
                .addGap(48, 48, 48)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(EmpezarPartidaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VerPartidasTerminadasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VerPartidasSinTerminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Barra.setBackground(new java.awt.Color(170, 57, 57));
        Barra.setPreferredSize(new java.awt.Dimension(750, 90));

        GitHubTexto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        GitHubTexto.setForeground(new java.awt.Color(255, 255, 255));
        GitHubTexto.setIcon(new javax.swing.ImageIcon("C:\\Users\\DAW_M\\Documents\\NetBeansProjects\\Juego-Batalla-Naval\\src\\main\\img\\github.png")); // NOI18N
        GitHubTexto.setText("marromagu");
        GitHubTexto.setIconTextGap(10);

        emailTexto.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        emailTexto.setForeground(new java.awt.Color(255, 255, 255));
        emailTexto.setText(" Hundir La Flota.");
        emailTexto.setPreferredSize(new java.awt.Dimension(100, 23));

        textoEjercicio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        textoEjercicio.setForeground(new java.awt.Color(255, 255, 255));
        textoEjercicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\DAW_M\\Documents\\NetBeansProjects\\Juego-Batalla-Naval\\src\\main\\img\\gmail_1.png")); // NOI18N
        textoEjercicio.setText("mromagu2611@g.educaand.es");
        textoEjercicio.setIconTextGap(10);

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(GitHubTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoEjercicio)
                .addGap(33, 33, 33)
                .addComponent(emailTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(852, 852, 852))
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GitHubTexto)
                    .addComponent(textoEjercicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(emailTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(758, 516));

        texto.setText("Mario Romero Aguilar");

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addComponent(texto)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgrounLayout = new javax.swing.GroupLayout(backgroun);
        backgroun.setLayout(backgrounLayout);
        backgrounLayout.setHorizontalGroup(
            backgrounLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgrounLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgrounLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(Barra, javax.swing.GroupLayout.DEFAULT_SIZE, 1462, Short.MAX_VALUE))
        );
        backgrounLayout.setVerticalGroup(
            backgrounLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(backgrounLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroun, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroun, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmpezarPartidaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpezarPartidaBotonActionPerformed

        ShowJPanel(new Ventana_EmpezarPartida(this));
    }//GEN-LAST:event_EmpezarPartidaBotonActionPerformed

    private void VerPartidasTerminadasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPartidasTerminadasBotonActionPerformed

        // ShowJPanel(new Ventana_Opcion2_VerT(this));
    }//GEN-LAST:event_VerPartidasTerminadasBotonActionPerformed

    private void VerPartidasSinTerminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPartidasSinTerminarBotonActionPerformed

        ShowJPanel(new Ventana_VerPartidaSinTerminar(this));
    }//GEN-LAST:event_VerPartidasSinTerminarBotonActionPerformed

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        miCliente.cerrarConexiones();
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatAtomOneDarkIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppModificada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton EmpezarPartidaBoton;
    private javax.swing.JLabel GitHubTexto;
    private javax.swing.JLabel Icono;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton VerPartidasSinTerminarBoton;
    private javax.swing.JButton VerPartidasTerminadasBoton;
    private javax.swing.JPanel backgroun;
    private javax.swing.JLabel emailTexto;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel textoEjercicio;
    // End of variables declaration//GEN-END:variables

    private void initStyle() {
        texto.putClientProperty("FlatLaf.styleClass", "h1");
        texto.setForeground(Color.WHITE);
    }

    public void ShowJPanel(JPanel p) {
        Contenido.removeAll();
        Contenido.add(p, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();

        p.setSize(700, 400);
        p.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(p, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }
}
