/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import Cliente.ConexionCliente;
import Ventanas.Ventana_Login;
import Ventanas.Ventana_Opciones;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author mario
 */
public class Ventana_Principal extends javax.swing.JFrame {

    ConexionCliente miCliente = ConexionCliente.getCliente();

    public ConexionCliente getMiCliente() {
        return miCliente;
    }

    /**
     * Creates new form App
     */
    public Ventana_Principal() {
        initComponents();
        InitContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        Fondo.setBackground(new java.awt.Color(204, 255, 204));
        Fondo.setPreferredSize(new java.awt.Dimension(1200, 800));

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    // End of variables declaration//GEN-END:variables
    private void InitContent() {//Ventana de inicio
        Ventana_Login miInicio = new Ventana_Login(this);
        miInicio.setSize(400, 300);
        miInicio.setLocation(0, 0);

        Fondo.removeAll();
        Fondo.add(miInicio, BorderLayout.CENTER);
        Fondo.revalidate();
        Fondo.repaint();

    }

    public void showOpcionesPanel() {
        // Cerrar el panel actual
        Fondo.removeAll();
        Fondo.revalidate();
        Fondo.repaint();

        // Crear y mostrar el nuevo panel (Ventana_Opciones)
        Ventana_Opciones opcionesPanel = new Ventana_Opciones(this);
        opcionesPanel.setSize(1200, 800);
        opcionesPanel.setLocation(0, 0);

        Fondo.removeAll();
        Fondo.add(opcionesPanel, BorderLayout.CENTER);
        Fondo.revalidate();
        Fondo.repaint();
    }

    public void ShowJPanel(JPanel p) {
      
        p.setSize(1200, 800);
        p.setLocation(0, 0);

        Fondo.removeAll();
        Fondo.add(p, BorderLayout.CENTER);
        Fondo.revalidate();
        Fondo.repaint();
    }
}
