/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.AppModificada;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class Ventana_VerPartidaMiTurno extends javax.swing.JPanel {

    private AppModificada miApp; // Agrega una referencia a la instancia de Ventana_Principal

    /**
     * Creates new form VentanaOpcionesEmpezarPartida
     *
     * @param app
     */
    public Ventana_VerPartidaMiTurno(AppModificada app) {
        initComponents();
        this.miApp = app; // Asigna la referencia de Ventana_Principal
        initializeButton();
        mostarListaDePartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPartidas = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 500));

        BackGround.setPreferredSize(new java.awt.Dimension(700, 500));

        jButtonBack.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Atras");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        TablaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Id Partida", "Jugador 1", "Jugador 2", "Ultimo Turno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPartidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(TablaPartidas);

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBack)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        miApp.ShowJPanel(new Ventana_VerPartidaSinTerminar(miApp));
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JTable TablaPartidas;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void initializeButton() {
        jButtonBack.addActionListener((java.awt.event.ActionEvent evt) -> {
            // Vuelve a la ventana VentanaOpciones
            miApp.ShowJPanel(new Ventana_VerPartidaSinTerminar(miApp));
        });
    }

    private void mostarListaDePartida() {
        DefaultTableModel modelo = (DefaultTableModel) TablaPartidas.getModel();
        modelo.setRowCount(0); // Limpiar todas las filas

        //Actualizar partidas mi turno
        miApp.getMiCliente().actualizarListaDePartidasSinTerminarMiTurno();

        HashMap<Integer, String> listaDePartidas = miApp.getMiCliente().getMisDatos().getListaPartidasMiTurno();

        for (Map.Entry<Integer, String> partida : listaDePartidas.entrySet()) {
            String[] datosPartida = partida.getValue().split(",");

            // Asegurarse de que hay suficientes datos para llenar las columnas
            if (datosPartida.length == 4) {
                modelo.addRow(new Object[]{
                    Integer.parseInt(datosPartida[0]), // Id Partida
                    datosPartida[1], // Jugador 1
                    datosPartida[2], // Jugador 2
                    datosPartida[3] // Último Turno
                });
            }
        }
        // Asegurarse de que la Tabla se actualiza
        modelo.fireTableDataChanged();

        // Centrar datos en la tabla
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        for (int i = 0; i < TablaPartidas.getColumnCount(); i++) {
            TablaPartidas.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Agrega un listener de eventos de raton a la tabla
        TablaPartidas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) { // Doble clic
                    int filaSeleccionada = TablaPartidas.getSelectedRow();
                    if (filaSeleccionada != -1) {
                        // Obtiene el valor de la columna "Id Jugador" de la fila seleccionada
                        int idPartidaSeleccionada = (int) TablaPartidas.getValueAt(filaSeleccionada, 0);

                        // Muestra la ventana o realiza la acción que deseas con el idJugadorSeleccionado
                        mostrarVentana(idPartidaSeleccionada);
                    }
                }
            }

            private void mostrarVentana(int idPartidaSeleccionada) {
                miApp.ShowJPanel(new Ventana_VerPartidaMiTurnoDisparar(miApp, idPartidaSeleccionada));
            }
        });
    }
}
