/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.AppModificada;
import java.util.ArrayList;

/**
 *
 * @author mario
 */
public class Ventana_VerPartidaTerminadaRepeticion extends javax.swing.JPanel {

    private final AppModificada miApp; // Agrega una referencia a la instancia de Ventana_Principal
    private final int id;
    private int i = 0;

    /**
     * Creates new form VentanaOpcionesEmpezarPartida
     *
     * @param app
     * @param id_partida
     */
    public Ventana_VerPartidaTerminadaRepeticion(AppModificada app, String id_partida) {
        initComponents();
        this.miApp = app; // Asigna la referencia de Ventana_Principal
        initializeButton();
        jLabel1.setText("Id Partida: " + id_partida);
        id = Integer.parseInt(id_partida);
        mostarListaDeDisparos();
        BotonSiguiente.setEnabled(true);
        // Hacer que el JTextArea no sea editable
        Log_DeDisparos.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Log_DeDisparos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        BotonSiguiente = new javax.swing.JToggleButton();
        jButtonBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 500));

        BackGround.setPreferredSize(new java.awt.Dimension(700, 500));

        Log_DeDisparos.setColumns(20);
        Log_DeDisparos.setRows(5);
        jScrollPane1.setViewportView(Log_DeDisparos);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N

        BotonSiguiente.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        BotonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Atras");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                        .addGap(0, 96, Short.MAX_VALUE)
                        .addComponent(jButtonBack)))
                .addContainerGap())
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonSiguiente)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBack)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        ArrayList<String> disparosRepeticion = miApp.getMiCliente().repeticion(id);

        if (i < disparosRepeticion.size()) {
            // Muestra el elemento actual y pasa al siguiente índice
            Log_DeDisparos.append(disparosRepeticion.get(i++) + "\n");
        } else {
            // Muestra un mensaje cuando se alcanza el final del array
            Log_DeDisparos.append("- Fin de la lista- \n");

            // Desactiva el botón "Siguiente" al final de la lista
            BotonSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        miApp.ShowJPanel(new Ventana_VerPartidaTerminada(miApp));
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JToggleButton BotonSiguiente;
    private javax.swing.JTextArea Log_DeDisparos;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initializeButton() {
        jButtonBack.addActionListener((java.awt.event.ActionEvent evt) -> {
            // Vuelve a la ventana Opcion 2 Ver Partida
            miApp.ShowJPanel(new Ventana_VerPartidaTerminada(miApp));
        });
    }

    private void mostarListaDeDisparos() {
        Log_DeDisparos.setText("-Pulsa Siguiente-\n");
    }
}
