/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.Ventana_Principal;

/**
 *
 * @author mario
 */
public class Ventana_Opciones extends javax.swing.JPanel {

    private Ventana_Principal miApp; // Agrega una referencia a la instancia de Ventana_Principal

    /**
     * Creates new form VentanaOpciones
     */
    public Ventana_Opciones(Ventana_Principal app) {
        initComponents();
        this.miApp = app; // Asigna la referencia de Ventana_Principal
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        verPartidaTerminadaBoton = new javax.swing.JButton();
        empezarPartidaBoton = new javax.swing.JButton();
        verPartidaMiTurno = new javax.swing.JButton();
        verPartidaSuTurno = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        verPartidaTerminadaBoton.setText("Ver partidas ya terminadas");
        verPartidaTerminadaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPartidaTerminadaBotonActionPerformed(evt);
            }
        });

        empezarPartidaBoton.setText("Empezar Partida");
        empezarPartidaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarPartidaBotonActionPerformed(evt);
            }
        });

        verPartidaMiTurno.setText("Ver resto de partidas sin terminar (mi turno)");
        verPartidaMiTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPartidaMiTurnoActionPerformed(evt);
            }
        });

        verPartidaSuTurno.setText("Ver resto de partidas sin terminar (su turno)");
        verPartidaSuTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPartidaSuTurnoActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empezarPartidaBoton)
                    .addComponent(verPartidaTerminadaBoton)
                    .addComponent(verPartidaMiTurno)
                    .addComponent(verPartidaSuTurno)
                    .addComponent(jButton1))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empezarPartidaBoton)
                .addGap(18, 18, 18)
                .addComponent(verPartidaTerminadaBoton)
                .addGap(18, 18, 18)
                .addComponent(verPartidaMiTurno)
                .addGap(18, 18, 18)
                .addComponent(verPartidaSuTurno)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empezarPartidaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarPartidaBotonActionPerformed
        miApp.ShowJPanel(new Ventana_Opcion1_EP(miApp));
    }//GEN-LAST:event_empezarPartidaBotonActionPerformed

    private void verPartidaTerminadaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPartidaTerminadaBotonActionPerformed
        miApp.ShowJPanel(new Ventana_Opcion2_VerT(miApp));
    }//GEN-LAST:event_verPartidaTerminadaBotonActionPerformed

    private void verPartidaMiTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPartidaMiTurnoActionPerformed
        miApp.ShowJPanel(new Ventana_Opcion3_VerMi(miApp));
    }//GEN-LAST:event_verPartidaMiTurnoActionPerformed

    private void verPartidaSuTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPartidaSuTurnoActionPerformed
        miApp.ShowJPanel(new Ventana_Opcion4_VerSu(miApp));
    }//GEN-LAST:event_verPartidaSuTurnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        miApp.getMiCliente().cerrarConexiones();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton empezarPartidaBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton verPartidaMiTurno;
    private javax.swing.JButton verPartidaSuTurno;
    private javax.swing.JButton verPartidaTerminadaBoton;
    // End of variables declaration//GEN-END:variables
}
