/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.AppModificada;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class Ventana_EmpezarPartidaJugar extends javax.swing.JPanel {

    private final AppModificada miApp; // Agrega una referencia a la instancia de Ventana_Principal
    private final int id_partida;
    private final int idJugador2;

    /**
     * Creates new form VentanaOpcionesEmpezarPartida
     *
     * @param app
     * @param id_partida
     */
    public Ventana_EmpezarPartidaJugar(AppModificada app, int id_partida, int idJugador2) {
        initComponents();
        this.miApp = app;
        this.id_partida = id_partida;
        this.idJugador2 = idJugador2;

        String textoActual = Titulo.getText();
        String nuevoTexto = textoActual + this.id_partida;
        Titulo.setText(nuevoTexto);

        // Crear una instancia de la clase Ventana_EmpezarPartidaJugarTablero
        Ventana_EmpezarPartidaJugarTablero tablero = new Ventana_EmpezarPartidaJugarTablero(app);

        // Configurar el GridLayout para el tablero
        tablero.setLayout(new GridLayout(10, 10));

        // Establecer el color de fondo del tablero
        tablero.setBackground(Color.WHITE);

        // Añadir el tablero al contenedor Tablero
        ShowJTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        BackGround = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        CoordenadaX = new javax.swing.JTextField();
        CoordenadaY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonDisparo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Tablero = new javax.swing.JPanel();

        jScrollPane2.setViewportView(jTextPane1);

        setPreferredSize(new java.awt.Dimension(700, 500));

        BackGround.setPreferredSize(new java.awt.Dimension(700, 500));

        jButtonBack.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Atras");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Coordenada X");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Coordenada Y");

        BotonDisparo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        BotonDisparo.setForeground(new java.awt.Color(255, 255, 255));
        BotonDisparo.setText("Disparar");
        BotonDisparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDisparoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canon.png"))); // NOI18N

        Titulo.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Partida: ");

        Tablero.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout TableroLayout = new javax.swing.GroupLayout(Tablero);
        Tablero.setLayout(TableroLayout);
        TableroLayout.setHorizontalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        TableroLayout.setVerticalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBack))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackGroundLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                                .addGap(0, 126, Short.MAX_VALUE)
                                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CoordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CoordenadaY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(BotonDisparo, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoordenadaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(BotonDisparo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(72, 72, 72)
                .addComponent(jButtonBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        miApp.ShowJPanel(new Ventana_EmpezarPartida(miApp));
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void BotonDisparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDisparoActionPerformed

        try {
            // Obtener el contenido de los campos de texto
            String coordenadaXText = CoordenadaX.getText();
            String coordenadaYText = CoordenadaY.getText();

            // Convertir las cadenas a enteros
            int x = Integer.parseInt(coordenadaXText);
            int y = Integer.parseInt(coordenadaYText);
            boolean disparo;

            // Realizar la operación con los valores numéricos
            disparo = miApp.getMiCliente().hacerDisparo(id_partida, x, y);
            // Mostrar mensaje emergente según el resultado del disparo
            if (disparo) {
                JOptionPane.showMessageDialog(this, "¡Tocado!", "Resultado del Disparo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Agua", "Resultado del Disparo", JOptionPane.INFORMATION_MESSAGE);
            }
            CoordenadaX.setText("");
            CoordenadaY.setText("");
        } catch (NumberFormatException e) {
            // Manejar la excepción si ocurre un error al convertir a entero
            CoordenadaX.setText("");
            CoordenadaY.setText("");
            JOptionPane.showMessageDialog(this, "Por favor, ingrese números válidos en las coordenadas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonDisparoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BotonDisparo;
    private javax.swing.JTextField CoordenadaX;
    private javax.swing.JTextField CoordenadaY;
    private javax.swing.JPanel Tablero;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    // Método para mostrar un panel en el contenedor del tablero
    public void ShowJTablero() {
        Ventana_EmpezarPartidaJugarTablero miTablero = new Ventana_EmpezarPartidaJugarTablero(miApp);
        miTablero.setSize(300, 300);
        miTablero.setLocation(0, 0);

        Tablero.removeAll();
        Tablero.add(miTablero, new GridLayout(10, 10));
        Tablero.revalidate();
        Tablero.repaint();
    }
}
