/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.AppModificada;

/**
 *
 * @author DAM_M
 */
public class Ventana_VerPartidaSinTerminar extends javax.swing.JPanel {

    AppModificada miApp = new AppModificada();
    /**
     * Creates new form Ventana_VerPartidaSinTerminar
     */
    public Ventana_VerPartidaSinTerminar(AppModificada miApp) {
        this.miApp = miApp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        MiTurno = new javax.swing.JButton();
        SuTurno = new javax.swing.JButton();

        MiTurno.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        MiTurno.setForeground(new java.awt.Color(0, 255, 59));
        MiTurno.setText("Ver Partidas Sin Terminar (Mi Turno)");
        MiTurno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        MiTurno.setBorderPainted(false);
        MiTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiTurno.setIconTextGap(10);
        MiTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiTurnoActionPerformed(evt);
            }
        });

        SuTurno.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        SuTurno.setForeground(new java.awt.Color(255, 0, 22));
        SuTurno.setText("Ver Partidas Sin Terminar (Su Turno)");
        SuTurno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SuTurno.setBorderPainted(false);
        SuTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SuTurno.setIconTextGap(10);
        SuTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SuTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(MiTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(MiTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(SuTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MiTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiTurnoActionPerformed
        miApp.ShowJPanel(new Ventana_VerPartidaMiTurno(miApp));
    }//GEN-LAST:event_MiTurnoActionPerformed

    private void SuTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuTurnoActionPerformed
        miApp.ShowJPanel(new Ventana_VerPartidaSuTurno(miApp));
    }//GEN-LAST:event_SuTurnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton MiTurno;
    private javax.swing.JButton SuTurno;
    // End of variables declaration//GEN-END:variables
}
