/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.AppModificada;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class Ventana_VerPartidaTerminada extends javax.swing.JPanel {

    private AppModificada miApp; // Agrega una referencia a la instancia de Ventana_Principal

    /**
     * Creates new form VentanaOpcionesEmpezarPartida
     *
     * @param app
     */
    public Ventana_VerPartidaTerminada(AppModificada app) {
        initComponents();
        this.miApp = app; // Asigna la referencia de Ventana_Principal;
        llenarTablaConDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        id_ParitdaJLabel = new javax.swing.JLabel();
        id_PartidaJTextField = new javax.swing.JTextField();
        verJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPartidas = new javax.swing.JTable();

        id_ParitdaJLabel.setText("Id Paritda");

        verJButton.setText("Ver");
        verJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verJButtonActionPerformed(evt);
            }
        });

        TablaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Partida", "Jugador 1", "Jugador 2", "Ganador", "Ultimo Turno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaPartidas);

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id_ParitdaJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id_PartidaJTextField))
                .addGap(18, 18, 18)
                .addComponent(verJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addComponent(id_ParitdaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_PartidaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verJButton))))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verJButtonActionPerformed
        String id_partida;
        id_partida = id_PartidaJTextField.getText();
        miApp.ShowJPanel(new Ventana_VerPartidaTerminadaRepeticion(miApp, id_partida));
    }//GEN-LAST:event_verJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JTable TablaPartidas;
    private javax.swing.JLabel id_ParitdaJLabel;
    private javax.swing.JTextField id_PartidaJTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton verJButton;
    // End of variables declaration//GEN-END:variables

    private void llenarTablaConDatos() {
        DefaultTableModel model = (DefaultTableModel) TablaPartidas.getModel();
        model.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos

        // Obtén la lista de partidas terminadas desde la aplicación
        HashMap<Integer, String> partidas = miApp.getMiCliente().getMisDatos().getListaPartidaTermindas();

        // Itera sobre la lista y agrega cada partida a la tabla
        for (HashMap.Entry<Integer, String> entrada : partidas.entrySet()) {
            Scanner sc = new Scanner(entrada.getValue());
            sc.useDelimiter(";");
            // Verifica la existencia de los elementos antes de acceder a ellos

            int idPartida = sc.nextInt();
            String nombreJugador1 = sc.next();
            String nombreJugador2 = sc.next();
            String nombreGanador = sc.next();
            String nombreUltimoTurno = sc.next();

            // Agrega los datos a la tabla
            model.addRow(new Object[]{idPartida, nombreJugador1, nombreJugador2, nombreGanador, nombreUltimoTurno});

            sc.close();
        }
    }
}
