/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.Ventana_Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class Ventana_Login extends javax.swing.JPanel {

    /**
     * Creates new form Ventana_Login
     */
    private Ventana_Principal miApp; // Agrega una referencia a la instancia de Ventana_Principal

    public Ventana_Login(Ventana_Principal app) {
        initComponents();
        this.miApp = app; // Asigna la referencia de Ventana_Principal
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        enviarJButton = new javax.swing.JButton();
        usuarioJLabel = new javax.swing.JLabel();
        contraseñaJLabel = new javax.swing.JLabel();
        usuarioJTextField = new javax.swing.JTextField();
        contraseñaJTextField = new javax.swing.JTextField();

        enviarJButton.setText("Enviar");
        enviarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarJButtonActionPerformed(evt);
            }
        });

        usuarioJLabel.setText("Usuario");

        contraseñaJLabel.setText("Contraseña");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseñaJLabel)
                    .addComponent(usuarioJLabel))
                .addGap(44, 44, 44)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enviarJButton)
                    .addComponent(usuarioJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(contraseñaJTextField))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioJLabel)
                    .addComponent(usuarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaJLabel)
                    .addComponent(contraseñaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(enviarJButton)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enviarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarJButtonActionPerformed

        String usuario = usuarioJTextField.getText();
        String contraseñaString = contraseñaJTextField.getText();
        int contraseña = Integer.parseInt(contraseñaString);
        if (!miApp.getMiCliente().login(usuario, contraseña)) {
            // Muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "Datos incorrectos", "Error de autenticación", JOptionPane.ERROR_MESSAGE);

            // Borra los campos de texto
            usuarioJTextField.setText("");
            contraseñaJTextField.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Bienvenido " + JOptionPane.YES_OPTION);
            // Muestra el panel de opciones
            miApp.showOpcionesPanel();
        }
    }//GEN-LAST:event_enviarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel contraseñaJLabel;
    private javax.swing.JTextField contraseñaJTextField;
    private javax.swing.JButton enviarJButton;
    private javax.swing.JLabel usuarioJLabel;
    private javax.swing.JTextField usuarioJTextField;
    // End of variables declaration//GEN-END:variables
}
