/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import App.AppModificada;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class Ventana_EmpezarPartida extends javax.swing.JPanel {

    private final AppModificada miApp; // Agrega una referencia a la instancia de AppModificada

    /**
     * Creates new form VentanaOpcionesEmpezarPartida
     *
     * @param app
     */
    public Ventana_EmpezarPartida(AppModificada app) {
        initComponents();
        this.miApp = app; // Asigna la referencia de AppModificada
        tablaJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaJugadores = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 400));

        BackGround.setPreferredSize(new java.awt.Dimension(700, 400));

        TablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Id Jugador", "Nombre Jugador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaJugadores);

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JTable TablaJugadores;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void tablaJugadores() {
        DefaultTableModel modelo = (DefaultTableModel) TablaJugadores.getModel();
        modelo.setRowCount(0); // Limpiar todas las filas

        HashMap<Integer, String> usuario = miApp.getMiCliente().getListaUsuario();

        for (Map.Entry<Integer, String> entry : usuario.entrySet()) {
            Integer idJugador = entry.getKey();
            String nombreJugador = entry.getValue();

            modelo.addRow(new Object[]{idJugador, nombreJugador});
        }

        // Asegurarse de que la Tabla se actualiza
        modelo.fireTableDataChanged();

        // Centrar datos en la tabla
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        for (int i = 0; i < TablaJugadores.getColumnCount(); i++) {
            TablaJugadores.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        // Agrega un listener de eventos de raton a la tabla
        TablaJugadores.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) { // Doble clic
                    int filaSeleccionada = TablaJugadores.getSelectedRow();
                    if (filaSeleccionada != -1) {
                        // Obtiene el valor de la columna "Id Jugador" de la fila seleccionada
                        int idJugadorSeleccionado = (int) TablaJugadores.getValueAt(filaSeleccionada, 0);

                        // Muestra la ventana o realiza la acción que deseas con el idJugadorSeleccionado
                        mostrarVentana(idJugadorSeleccionado);
                    }
                }
            }
        });
    }

    private void mostrarVentana(int idJugador2) {
        if (idJugador2 == miApp.getMiCliente().getMisDatos().getIdJugador()) {
            JOptionPane.showMessageDialog(this, "No puedes Jugar una partida contigo mismo.");
        } else {
            JOptionPane.showMessageDialog(this, "Partida empezada contra: " + idJugador2);
            int id_partida = miApp.getMiCliente().crearNuevaPartida(idJugador2);
            miApp.ShowJPanel(new Ventana_EmpezarPartidaJugar(miApp, id_partida));
        }
    }
}
